### ISSUE TITLE
Build and Install on Centos 7.x with SSL and TLS support

### ISSUE THREAD

**Issue by noahmehl** [sipcapture/captagent#176]
When I try to build Captagent with TLS and SSL on Centos 7, I get the following error:

`make[3]: Entering directory `/usr/local/src/captagent/src/modules/protocol/tcp'
Making all in .
make[4]: Entering directory `/usr/local/src/captagent/src/modules/protocol/tcp'
  CC       protocol_tcp_la-protocol_tcp.lo
  CC       protocol_tcp_la-localapi.lo
  CC       protocol_tcp_la-parser_tls.lo
parser_tls.c: In function 'ssl_cipher_init':
parser_tls.c:204:42: error: 'GCRY_CIPHER_MODE_GCM' undeclared (first use in this function)
     err = gcry_cipher_open(cipher, algo, GCRY_CIPHER_MODE_GCM, 0);
                                          ^
parser_tls.c:204:42: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [protocol_tcp_la-parser_tls.lo] Error 1
make[4]: Leaving directory `/usr/local/src/captagent/src/modules/protocol/tcp'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/usr/local/src/captagent/src/modules/protocol/tcp'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/local/src/captagent/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/captagent/src'
make: *** [all-recursive] Error 1`

These are my libgcrypt versions:

# rpm -qa | grep gcrypt
libgcrypt-1.5.3-14.el7.x86_64
libgcrypt-devel-1.5.3-14.el7.x86_64

Please let me know if I'm doing something wrong here, or, please let me know if it's possible to support TLS and SSL with 1.5.3 of gcrypt.

Thanks!

**Comment by noahmehl** [comment]
Also, I tried to do this from master today.

**Comment by noahmehl** [comment]
This is also failing with the same error in tag 6.3.0.

**Comment by lmangani** [comment]
Hi @noahmehl i'm afraid this only works with libgcrypt 1.8 or higher

**Comment by kYroL01** [comment]
@noahmehl , as Lorenzo said, you must upgrade your libgcrypt library to version 1.8.
Try and let us know about it.
Thanks

**Comment by lmangani** [comment]
Extended wiki to clarify the library version. https://github.com/sipcapture/captagent/wiki/TLS
@noahmehl feel free to extend in case of issues or for any advice

**Comment by noahmehl** [comment]
This is kinda problematic, because I know of no way to do this on CentOS 7....

**Comment by lmangani** [comment]
@noahmehl is it not in EPEL? Before you invest time and efforts, are you positive your encryption is supported?

**Comment by noahmehl** [comment]
@lmangani I do not believe that it is in EPEL either.

Looks like I can restrict the ciphers in Kamailio and probably will to the list that's currently supported.

**Comment by lmangani** [comment]
Out of curiosity - why not capturing directly from within Kamailio if that's the point of encryption? Or you mean publishing support for limited ciphers from Kamailio to have it matched forcefully by the "other side"?

**Comment by noahmehl** [comment]
Apparently, this has come up?

https://github.com/sipcapture/homer/wiki/Examples:-Kazoo

**Comment by lmangani** [comment]
@noahmehl we can help with professional services if needed, its always best not to break your own encryption unless its the only resort - Freeswitch does not support RTCP, but we do through ESL adaptors such as `hepipe.js` converting FS events into HEP events

**Comment by noahmehl** [comment]
So, adding sip tracing to the kazoo configs was hilariously easy.  I'll take a look at the hepipe.js ESL integration.  Looking great :)
